### ISSUE TITLE
依存パッケージの脆弱性の問題を解決する

### ISSUE THREAD

**Issue by dino3616** [shikosai32/shikosai.net#14]
- https://github.com/shikosai32/shikosai.net/runs/7401835249?check_suite_focus=true

# 確認された脆弱性のある依存パッケージ
- @typescript-eslint/eslint-plugin - > glob-parent
- @typescript-eslint/parser - > glob-parent
- tailwindcss - > glob-parent
- moment

**Comment by dino3616** [comment]
`moment`は`2.29.4`に上げることで対処可能。
他は`glob-parent`の脆弱性が伝播しているため、以下の何れかで対処する必要がありそう。
- それぞれのパッケージが最新の`glob-parent`を導入してくれるのを待つ。
- それぞれのパッケージをダウングレードする。
- `yarn audit`をテストから外す。

どなたか判断お願いします🙏

**Comment by Yusuke4869** [comment]
`moment` は最新バージョンに上げましょう
